### ISSUE TITLE
Example output error in chapter 3.2. Muuttujan esittely 

### ISSUE THREAD

**Issue by syyspe** [materiaalit/ohjelmointi-18#1]
There is an inconsistency in the example between the source code, and the output of the program. The example code is as follows:

public class Esimerkki {
    public static void main(String[] args) {
        int elamanTarkoitus = 123;
        double pii = 3.141592653;

        System.out.println("Elämän tarkoitus: " + elamanTarkoitus);
        System.out.println("Piin arvo on: " + pii);
    }
}

The output of this program would be: 

_Elämän tarkoitus: 123
Piin arvo on: 3.141592653_

But in the example the output is given as:

_Kokonaislukumuuttuja: 123
Liukulukumuuttuja: 3.141592653_

**Comment by Redande** [comment]
Fixed. Thanks for reporting this!
