### ISSUE TITLE
Tehtävä 19

### ISSUE THREAD

**Issue by EetuHakkinen** [materiaalit/ohjelmointi-18#10]
Tehtävän 19 ohjeet olivat erittäin epäselvät.
Käytännössä ohjeistuksen tehtävän tekemiseen sain NetBeansin antamista virheilmoituksista.
TOIVOISIN HUOMATTAVASTI PALJON PAREMPIA TEHTÄVÄNANTOJA!!!

**Comment by avihavai** [comment]
Hei Eetu, kerrotko minkä osan tehtävästä 19 on kyse ja voitko antaa muutamia konkreettisia esimerkkejä tehtävänannon epäselvyyksistä sekä siitä, miten toimit noissa tapauksissa?
