### ISSUE TITLE
4.1 Olioita listalla - Ikärajan voi kysyä myös käyttäjältä - luettu ikaraja ei ole käytössä mallissa ... ( koodattu: .. >= 18) { .. )

### ISSUE THREAD

**Issue by KariK2** [materiaalit/ohjelmointi-18#16]
Ikärajan voi kysyä myös käyttäjältä.

// ..
System.out.print("Mikä ikäraja? ");
int ikaraja = Integer.parseInt(lukija.nextLine());

for (Henkilo henkilo: henkilot) {
    if (henkilo.getIka() >= 18) {
        System.out.println(henkilo);
    }
}

**Comment by avihavai** [comment]
Kiitos! Tämä korjattu.
