### ISSUE TITLE
Virhe Aikakone-kysymyksessä

### ISSUE THREAD

**Issue by adex720** [materiaalit/ohjelmointi-18#18]
lukee:
public int setVuosi(int vuosi) {
        this.vuosi = vuosi;
    }  

pitäisi olla: 
public void setVuosi(int vuosi) {
        this.vuosi = vuosi;
    }  
tai public int setVuosi(int vuosi) {
        this.vuosi = vuosi;
        return this.vuosi;
    }

**Comment by avihavai** [comment]
Hei, tämä on nyt korjattu :+1:
