### ISSUE TITLE
Typo osa6,tehtävä 15 tehtävänannossa

### ISSUE THREAD

**Issue by smagis** [materiaalit/ohjelmointi-18#21]
Tietokoneelle ohjelmoitavan logiikan kuvauksessa sakset käsketään pelata myös silloin kun oikeasti pelattaisiin paperi.

"Sopivan valinnan etsiminen tehdään tarkastelemalla käyttäjän kahta viimeistä syötettä ja vertailemalla niitä koko historiaan. Mikäli historian mukaan kahta viimeistä syötettä seuraa useimmin kivi, tekoälyn tulee pelata **sakset**. Mikäli kahta viimeistä syötettä seuraa useimmin paperi, tekoälyn tulee pelata sakset."

**Comment by avihavai** [comment]
Tämä on korjattu, kiitos!
