### ISSUE TITLE
Osa 6, 8 - yhteenveto

### ISSUE THREAD

**Issue by tqre** [materiaalit/ohjelmointi-18#22]
Pelaajan viides siirto:

Siirrot:
0 1 0 1 1

Hajautustaulu:
0 1 0=1
1 0 1=1
0 1 1=1
0 1 1=1  <--- tämä rivi taitaa olla ylimääräinen? Lisäksi kahdennus toistuu myöhemmin.

Sitten esimerkkikoodista:
HashMap<String, Integer> muisti  = new ArrayList<>();
pitäisi olla:
HashMap<String, Integer> muisti = new HashMap<>();

Vielä:
System.out.println("Syötit " + syote + ", arvasin " + arvaus + ".");
System.out.println("Tietokoneen voitot: " + voitot);
System.out.println("Pelaajan voitot: " + (syotteet.size() - voitot));
-syote -muuttujaa ei ole määritelty

Pikakorjaus:
System.out.println("Syötit " + luku + ", arvasin " + arvaus + ".");
System.out.println("Tietokoneen voitot: " + voitot);
System.out.println("Pelaajan voitot: " + tappiot);

edit(kolmas tai neljäs):
Herää kysymys, ovatko nämä pienet virheet jätetty tuonne tarkoituksella, jotta suoraan copypastettuna koodi ei toimisi. Jos näin on, hyvä niin!

**Comment by avihavai** [comment]
Kiitos! Ei olla vielä niin pitkällä, että tarkoituksella jätettäisiin näitä :+1:
