### ISSUE TITLE
Osa 4, tehtävä 18: tehtävänanto epäselvä

### ISSUE THREAD

**Issue by jjaine** [materiaalit/ohjelmointi-18#23]
Tehtävänannossa ohjeistetaan käyttämään kaavaa `(maksimisyke - leposyke) * (tavoitesyke) + leposyke`, mikä on sinänsä harhaanjohtavaa että tavoitesykkeen sijaan halutaan käytettävän tavoitesykeprosenttia. 

Jos siis käytettäisiin kyseistä kaavaa tehtävänannon esimerkillä "henkilön maksimisyke on 200, leposyke 50, ja tavoitesyke 75% maksimisykkeestä", sijoitettaisiin arvot kaavaan näin: `(200-50)*(200*0.75)+50`, jolloin ei tietystikään saada halutunlaista tulosta. 

Tehtävänannon kaavan voisikin muotoilla uudelleen muotoon `(maksimisyke - leposyke) * (tavoitesykeprosentti) + leposyke`.

**Comment by avihavai** [comment]
Korjattu, kiitos! :+1:
