### ISSUE TITLE
osa7. 2.14: liikaa samannimisiä muuttujia, error: variable tehtava is already defined

### ISSUE THREAD

**Issue by tqre** [materiaalit/ohjelmointi-18#29]
Virheitä tuottava koodi:

    public void merkkaaTehdyksi(String tehtava) {
        for (Tehtava tehtava: tehtavat) {
            if (tehtava.getNimi().equals(tehtava)) {
                tehtava.setTehty(true);
            }
        }
    }

    public boolean onTehty(String tehtava) {
        for (Tehtava tehtava: tehtavat) {
            if (tehtava.getNimi().equals(tehtava) && tehtava.onTehty()) {
                return true;
            }
        }
        return false;
    }

Muutosehdotus:

    public void merkkaaTehdyksi(String tehdyksiMerkattavaTehtava) {
        for (Tehtava tehtava : tehtavat) {
            if (tehtava.getNimi().equals(tehdyksiMerkattavaTehtava)) {
                tehtava.setTehty(true);
            }
        }
    }

    public boolean onTehty(String tarkistettavaTehtava) {
        for (Tehtava tehtava : tehtavat) {
            if (tehtava.getNimi().equals(tarkistettavaTehtava) && tehtava.onTehty()) {
                return true;
            }
        }
        return false;
    }

(Edit: ulkoasu...)

**Comment by avihavai** [comment]
Kiitos, tämä korjattu! :+1:
