### ISSUE TITLE
Kirjoitusvirhe koodissa (Osa 1, tehtävä 3.5.)

### ISSUE THREAD

**Issue by lausau** [materiaalit/ohjelmointi-18#3]
Osa 1 Tehtävässä 3.5. jossa esitellään muuttujien nimentämistä kahdella esimerkillä, on ensimmäisen esimerkin koodissa kirjoitusvirhe. Koodissa lukee `System.out.println()` vaikka siinä pitäisi todennäköisesti lukea `System.out.println(c)` .

**Comment by Redande** [comment]
Hei, kiitos ilmoittamisesta! Kirjoitusvirhe on nyt korjattu.
