### ISSUE TITLE
Osa 7 tehtävä 4: Game of Life

### ISSUE THREAD

**Issue by smagis** [materiaalit/ohjelmointi-18#30]
"Esimerkiksi kohdassa (0, 0) oleva alkio on elossa jos kutsu taulukko.arvo(x, y) palauttaa arvon true. "

metodin nimi on hae eikä arvo

Edit: lisäksi osassa 4.2 puhutaan taulukon arvoista ykkösinä ja nollina booleaneitten sijasta.

**Comment by avihavai** [comment]
Korjattu, kiitos! :+1:
