### ISSUE TITLE
2.6. Olioiden yhtäsuuruuden vertailut - esimerkkikommentti hieman epäselvä

### ISSUE THREAD

**Issue by petrib** [materiaalit/ohjelmointi-18#31]
2.6. Olioiden yhtäsuuruuden vertailu 
...
public class Paivays {
...
// muunnetaan oli Paivays-olioksi
...

"oli" p.o. "verrattava olio" eli kokonaisuudessaan "// muunnetaan verrattava olio Paivays-olioksi"

**Comment by avihavai** [comment]
Korjattu, kiitos! :+1:
