### ISSUE TITLE
NetBeans with TMC 1.1.12 Memory / Processor usage problems

### ISSUE THREAD

**Issue by syyspe** [materiaalit/ohjelmointi-18#34]
Hello,

Not sure if this is something to report here, but reporting anyway just to make you aware:

NetBeans with TMC 1.1.12 started experiencing memory / processor usage issues during last week (w8/2018). It would stop responding completely for minutes, the NetBeans  window also started appearing / disappearing during these high resource usage spells. Attached screen from Windows 10 Taskmanager shows that the mem usage is nearly 1GB after one of these, the processor usage has already normalized in the screen, but it typically goes (and stys in) to 70 - 90 per cent during these.  Sometimes waiting few minutes would help, but after few of these the only option is to restart netbeans,

![javamem](https://user-images.githubusercontent.com/34917365/36778323-1e281c22-1c75-11e8-850a-2daf81dc650e.jpg)

**Comment by syyspe** [comment]
Possibly related to "checking for new exercises", today that task was running while this happened. Could be coincidence as well, I don't remember seeing that running in earlier instances of this.

**Comment by Redande** [comment]
Hey,

Could you send your NetBeans IDE log by email to mooc@cs.helsinki.fi please? You get the IDE log from NetBeans by pressing 'View' --> 'IDE log' from the nav bar. 

Also, how many projects do you have open currently? It's a known issue that if a student has too many projects open, the background scanning for each project can spike memory usage.

**Comment by syyspe** [comment]
Hello, 

IDE Log sent. Today part 8 projects + 2 open. Yesterday only 2 projects, no difference.

**Comment by syyspe** [comment]
It is getting very very very painful to use NetBeans... it constantly suddenly becomes slow as a snail.  The below entries are still numerous in the log, even after logout / login and  restart / logout / login.  TMC -> Settings says I'm logged in though, and I can see the return status indicator in submitted projects.

Log snippet:
SEVERE [fi.helsinki.cs.tmc.core.communication.TmcServerCommunicationTaskFactory]: Communication with the server failed!
INFO [fi.helsinki.cs.tmc.spyware.EventSendBuffer]: Sending failed
fi.helsinki.cs.tmc.core.exceptions.NotLoggedInException: Not logged in!

**Comment by syyspe** [comment]
Now I cannot submit Kertaus projects, after "submit" -> "waiting for results from server", the error dialog message says "Failed to process submission. Likely sent in incorrect format."  Log  doesn't contain anything like that error message though, there is just the "not logged in" errors.

**Comment by syyspe** [comment]
Submitting suddenly started working again.

**Comment by Redande** [comment]
We viewed the IDE log and made some fixes to get rid of the "Not logged in" problem. Could you please report back to us if the slowness has gone with the fix or if you're still experiencing the issue.

**Comment by syyspe** [comment]
Yes, thanks, slowness seems to be gone. It is working much better today morning.

**Comment by Redande** [comment]
Good to hear. Thanks for bringing the issue to our attention and helping us pinpoint the problem!
