### ISSUE TITLE
Osa 8, tehtävä 9.3, virhe esimerkkikoodissa

### ISSUE THREAD

**Issue by syyspe** [materiaalit/ohjelmointi-18#35]
Osan 8 tehtävä 9.3 esimerkkikoodissa on virhe, Luokan Varasto metodi tuotteet() palauttaa  Set\<String\> -tyyppisen olion, mutta   esimerkin for-each lause yrittää käyttää   Set\<Tuote\> tyyppistä oliota, luokkaa Tuote ei kuitenkaan ole tässä olemassa:

for (Tuote tuote: varasto.tuotteet()) {
    System.out.println(tuote);
}

--8<--
Tehtävä 9.3: Tuotteiden listaus
Listätään varastolle vielä yksi metodi:

public Set<String> tuotteet() palauttaa joukkona varastossa olevien tuotteiden nimet.
Metodi on helppo toteuttaa HashMapin avulla. Saat tietoon varastossa olevat tuotteet kysymällä ne joko hinnat tai saldot muistavalta Map:iltä metodin keySet avulla.

Esimerkki varaston käytöstä:

Varasto varasto = new Varasto();
varasto.lisaaTuote("maito", 3, 10);
varasto.lisaaTuote("kahvi", 5, 6);
varasto.lisaaTuote("piimä", 2, 20);
varasto.lisaaTuote("jugurtti", 2, 20);

System.out.println("tuotteet:");

for (Tuote tuote: varasto.tuotteet()) {
    System.out.println(tuote);
}
---8<---

**Comment by avihavai** [comment]
Kiitos, korjattu! :+1:
