### ISSUE TITLE
Osa 8, tehtävä 9, virhe kopioitavassa koodissa

### ISSUE THREAD

**Issue by smagis** [materiaalit/ohjelmointi-18#36]
Viimeisen osan Kauppa-luokan kopioitavassa koodissa rivien 19-21 for lauseen muuttujan nimi on väärin:

for (String **tuote**: varasto.tuotteet()) {
            System.out.println(**t**);
        }

Edit: koodia ei näemmä voinu boldata

**Comment by avihavai** [comment]
Korjattu, kiitos! :+1:
