### ISSUE TITLE
Reseptin raaka-aineet ja lista -> Epäselvä/epätäsmällinen lause

### ISSUE THREAD

**Issue by petrib** [materiaalit/ohjelmointi-18#38]
https://materiaalit.github.io/ohjelmointi-18/part6/

> Reseptin raaka-aineet ja lista
> 
> Yllä olevassa esimerkissä resepti lisätään listalle heti kun se on luotu. Kerro mitä tapahtuu reseptin raaka-aineille kun niitä lisätään reseptiin? **Kerro myös raaka-aineet löytyvät listalla olevasta reseptistä**, tai perustele miksi ne eivät löydy sieltä?

Ylläolevassa "Kerro myös raaka-aineet löytyvät listalla olevasta reseptistä" puutuu jotain (sana tai pari, jotta kysymys olisi selkeä.

**Comment by avihavai** [comment]
Korjattu muotoon "Kerro myös mitkä raaka-aineet löytyvät listalla olevasta reseptistä, tai perustele miksi ne eivät löydy sieltä?".
