### ISSUE TITLE
Osa 9, 5.3. Sama olio useammassa tietorakenteessa: virhe quizissa 

### ISSUE THREAD

**Issue by smagis** [materiaalit/ohjelmointi-18#40]
Kirjasto kirjasto = new Kirjasto();
Kirja **eka** = new Kirja("Catch-22", 46, "Lastenkirja");
Kirja toka = new Kirja("1984", 20, "Romantiikka");

kirjasto.lisaa(**kirja**);
kirjasto.lisaa(toka);
kirjasto.vaihdaGenre(46, "Romantiikka");
kirjasto.haeGenre(/* Parametri tähän */);

kirjastoon lisätään väärä muuttuja, kirjasto.lisaa(eka); olisi ilmeisesti oikein.

**Comment by avihavai** [comment]
Korjattu, kiitos!
