### ISSUE TITLE
Kirotusvihre kappaleessa 1. Käyttöliittymän ja sovelluslogiikan eriyttäminen

### ISSUE THREAD

**Issue by petrib** [materiaalit/ohjelmointi-18#42]
https://materiaalit.github.io/ohjelmointi-18/part7/

1. Käyttöliittymän ja sovelluslogiikan eriyttäminen 

...

Pohditaan uudestaan edellisen osan lopussa nähtyä kivi-paper-sakset -peliä sekä siihen liittyvää "tekoälyä".

Yllä "kivi-paper-sakset" p.o. "kivi-paper**i**-sakset" eli paperista puuttuu i.

**Comment by avihavai** [comment]
Korjattu, kiitos! :+1:
