### ISSUE TITLE
Osa 9 Tehtävä 5

### ISSUE THREAD

**Issue by Muksuluuri** [materiaalit/ohjelmointi-18#43]
Kohta 5.1: Ajettavasta esimerkkikoodista puuttui pilkku ja teksti "new".
Kohta 5.2: Ajettavasta esimerkkikoodista puuttuu Henkilo hay, Henkilo nacho ja puuttuu teksti "new".

**Comment by avihavai** [comment]
Kiitos, korjattu! :+1:
