### ISSUE TITLE
Osa 10 quiz "Filtteri" - oikea vastaus on väärä, vai miten sen sanoisi :)

### ISSUE THREAD

**Issue by syyspe** [materiaalit/ohjelmointi-18#45]
Filtteri -quiz väittää oikeaksi vastaukseksi että  6 lukua päätyy virran mukana lambda-lausekkeelle "i -> i > 10"?

Väitän että oikea vastaus on 4 :)

alussa: 0,1,2,3,4,5,6,7,8,9 
.filter(i -> i < 4), jää 0,1,2,3
.map(i -> i * 2), nyt 0,2,4,6
ja seuraavana on .filter(i -> i > 10), eli 0,2,4,6  - siis 4 lukua - tuli tänne asti, tästä eteenpäin ei mene yhtään.

sama testattuna tuottaa myös vastaukseksi "lukuja oli: 4":

```
List<Integer> luvut = new ArrayList<>();
for (int i = 0; i < 10; i++) {
        luvut.add(i);
}
long lukuja = luvut.stream().filter(i -> i < 4).map(i -> i * 2).count();
System.out.println("lukuja oli: " + lukuja);
```

**Comment by avihavai** [comment]
Äh.. 10 - 6 on tosiaankin 4 eikä 6, olet oikeassa :). Kiitos -- tämä on nyt korjattu!
