### ISSUE TITLE
Osa 7, 3.3. Toinen testi -> virhe tekstissä

### ISSUE THREAD

**Issue by petrib** [materiaalit/ohjelmointi-18#47]
https://materiaalit.github.io/ohjelmointi-18/part7/

> 3.3. Toinen testi 
> 
> ...
> 
> Testit toimi lainkaan, sillä luokasta Tehtavienhallinta puuttuu lisaa-metodi.

p.o. "Testi ei toimi lainakaan, sillä..."

**Comment by avihavai** [comment]
Korjattu, kiitos!
