### ISSUE TITLE
Mooc 2018  osa 09  - Tehtävä 1.1 ohjeessa nykyisellä tehtäväpohjalla pakkaus mooc taitaa olla jo olemassa

### ISSUE THREAD

**Issue by KariK2** [materiaalit/ohjelmointi-18#48]
Saatu ohje:
Tehtävä 1.1: Käyttöliittymä-rajapinta
Luo projektipohjaan pakkaus mooc. Rakennetaan tämän pakkauksen sisälle sovelluksen toiminta. Lisää pakkaukseen mooc pakkaus ui

Ilmeisesti halutaan luotavaksi jo olemassa olevan pakkauksen mooc alle ui ?

t. KariK

**Comment by avihavai** [comment]
Kiitos, tämä nyt korjattu! :+1:
