### ISSUE TITLE
Tehtävä 6: Uno (2 osaa) -> "Toiisaalta" p.o. "Toisaalta"

### ISSUE THREAD

**Issue by petrib** [materiaalit/ohjelmointi-18#49]
https://materiaalit.github.io/ohjelmointi-18/part7/

> Tehtävä 6: Uno (2 osaa)
> 
> ...
> 
> Vinkkejä viilaamiseen:
> 
> ...
> 
> Toiisaalta sitten, jos...

p.o. "Toisaalta".

**Comment by avihavai** [comment]
Korjattu, kiitos! :+1:
