### ISSUE TITLE
Tehtävä 10, osa 2, paikalliset testit eivät tunnista merkkijonoa

### ISSUE THREAD

**Issue by tqre** [materiaalit/ohjelmointi-18#59]
Jälleen serverille lähetettäessä kaikki on kunnossa, muuta paikalliset testit eivät tunnista ääkkösillä olevia tulostuksia:

Skandien kanssa siis ilmeisesti tämäkin tapahtuu, koitan katsoa, jos omat linuxin locale-asetukset ovat päin prinkkalaa tms.

Metodin tulostaAnalyysi kutsun tulee tulostaa rivi jossa on merkkijono "Suurin tuotemäärä:" org.junit.Assert.fail(Assert.java:88) org.junit.Assert.assertTrue(Assert.java:41) varastot.C_MuistavaTuotevarastoTest.tulostaAnalyysiSisaltaaHalututRivit(C_MuistavaTuotevarastoTest.java:248) sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) java.lang.reflect.Method.invoke(Method.java:498) org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47) org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44) org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17) org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26) org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271) org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70) org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50) org.junit.runners.ParentRunner$3.run(ParentRunner.java:238) org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63) org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236) org.junit.runners.ParentRunner.access$000(ParentRunner.java:53) org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229) org.junit.runners.ParentRunner.run(ParentRunner.java:309) fi.helsinki.cs.tmc.testrunner.TestRunner$TestingRunnable.runTestCase(TestRunner.java:134) fi.helsinki.cs.tmc.testrunner.TestRunner$TestingRunnable.doRun(TestRunner.java:89) fi.helsinki.cs.tmc.testrunner.TestRunner$TestingRunnable.run(TestRunner.java:70) java.lang.Thread.run(Thread.java:748)

**Comment by nygrenh** [comment]
Toi ongelma melko todennäköisesti on sun locale asetuksissa. Ongelma korjaantuu todennäköisesti jos muutat localesi joksikin UTF-8:n variantiksi.

Voitko kertoa mitä terminaalikomennot `locale` ja `locale -a` tulostavat sinun koneellasi?

**Comment by tqre** [comment]
Juu tämä selvisi. Plasma Desktoppi sotkee mun localet laittamalla sinne en_FI.UTF-8 localen, jota ei ole generoitu...
