### ISSUE TITLE
"Aina" sana ei esiinny

### ISSUE THREAD

**Issue by dmitrymarokhonov** [materiaalit/ohjelmointi-18#61]
Ennustaja ennustaja = new Ennustaja();
ennustaja.lisaa(true, "minulla on rohkeutta");
ennustaja.lisaa(true, "olen positiivisesti ajatteleva ja yhteistyökykyinen");
ennustaja.lisaa(true, "olen valmis valtuustoon");
ennustaja.lisaa(false, "olen ollut aktiivinen kuntapolitiikassa");
ennustaja.lisaa(false, "olen ollut yhteiskunnan asioissa aina aktiivinen toimija");
ennustaja.lisaa(false, "haluan olla valtuustossa");

System.out.println(ennustaja.valitaanSanojenLukumaariinPerustuen("haluan valtuustoon"));
System.out.println(ennustaja.valitaanSanojenLukumaariinPerustuen("olen aktiivinen toimija"));
System.out.println(ennustaja.valitaanSanojenLukumaariinPerustuen("olen yhteistyökykyinen"));
![image](https://user-images.githubusercontent.com/19345473/38311051-d2bb7b6c-3826-11e8-8c71-adc4105e1f2d.png)

Tapaus koskee tehtävää 12.14 Vaalipuheen tarkastaja: mielestäni sana "aina" ei esiinny kertaakaan, eikä sitä pidä olla olleenkaan listassa

**Comment by dmitrymarokhonov** [comment]
Korjaus, sanan "aina" pitää olla "Esiintymisiä valintaan johtamattomissa lauseissa" sarakkeessa

**Comment by Redande** [comment]
Kiitos ilmoituksesta, korjattu!
