### ISSUE TITLE
Toistolauseen käyttö merkkojonon kanssa - esimerkin kuvaus ei vastaa koodia ("loppu" vs. "")

### ISSUE THREAD

**Issue by syyspe** [materiaalit/ohjelmointi-18#7]
Kuvaus:

"Toistolauseen käyttö merkkijonojen kanssa käy samalla tavalla kuin muiden muuttujien kanssa. Alla olevassa esimerkissä luetaan käyttäjältä merkkijonoja, kunnes käyttäjä syöttää merkkijonon "loppu". Tämän jälkeen tulostetaan pisin merkkijono sekä pisimmän merkkijonon pituus."

koodi:

System.out.println("Syötä sana, tyhjä lopettaa.");
    String syote = lukija.nextLine();

    if (syote.equals("")) {
        break;
    }

**Comment by avihavai** [comment]
Kiitti, tämä nyt korjattu :+1:
