### ISSUE TITLE
Sivua ei löytynyt

### ISSUE THREAD

**Issue by jusa2018** [materiaalit/ohjelmointi-18#77]
Tenttien tiedot, ilmoittautumisohjeet, sekä tiedot arvostelusta löydät osoitteesta : http://mooc.fi/courses/2018/ohjelmoinnin-mooc/

**Comment by nygrenh** [comment]
Kiitos ongelman ilmoituksesta. Linkin pitäisi toimia nyt, kunhan vaan selaimeesi talletettu kopio sivusta vanhenee.

Pääset samalle sivulle myös jos menet menet osoitteeseen https://mooc.fi ja valitset "Ohjelmoinnin MOOC".
