### ISSUE TITLE
Osan 6 tehtävässä 13.1 kirjoitusvirhe

### ISSUE THREAD

**Issue by Tiim0ne** [materiaalit/ohjelmointi-18#89]
Tehtävänannossa pyydetään tekemään  konstruktori "public Kirja(String _niemeke_, String julkaisija, int julkaisuvuosi)" kun looginen olisi  public Kirja(String _nimike_, String julkaisija, int julkaisuvuosi)

**Comment by Redande** [comment]
Kiitos! Korjattu pull requestissa #90
