### ISSUE TITLE
Osan 8 ensimmäiseen Quiz-tehtävään liittyen

### ISSUE THREAD

**Issue by nea201811** [materiaalit/ohjelmointi-18#91]
Ellei itseltäni jäänyt huomaamatta jotain olennaista, ohjelman tulostuksen pitäisi olla
true
false
true
true
Muistio-luokan equals-metodissa kun ei lainkaan verrata muuttujaa vuosi. Tehtävä kuitenkin ilmoittaa, että kyseinen vastaus on väärin.

**Comment by mmxw11** [comment]
Kyllä se Quiz-tehtävä vaikuttaa olevan ihan oikein. Katso tarkkaan mitä se nimi-muuttujan equals-metodi saa parametrikseen.
